### ISSUE TITLE
libcrane not working in rootless?

### ISSUE THREAD

**Issue by cymouseX** [opa334/Crane-Resources#10]
libcrane not working in rootless?, i think it's not supported

**Comment by opa334** [comment]
It definitely works - Crane itself uses it...

**Comment by opa334** [comment]
Obviously you have to change `loadLibCrane` to load it from the correct path.

**Comment by cymouseX** [comment]
many thank , my idol

**Comment by cymouseX** [comment]
working ! perfect, thanks bro
