### ISSUE TITLE
Crane using default vendor ID for all containers.

### ISSUE THREAD

**Issue by savibb** [opa334/Crane-Resources#15]
When using crane with more than one container, the app will always receive the default container’s vendor ID. The different combinations of the buttons/toggles in crane’s preferences seem to be ineffective. The only way to ensure the app sees a different ID is to change the default container’s ID. (Used the Branch Metrics Inc device ID finder to measure)

^^iPhone 12 Pro Max iOS 16.1.2
Dopamine 2.2.2, Crane 1.3.16

I also have another 12 Pro Max on iOS 15.1, this issue doesn’t seem to exist on the older phone.

**Comment by opa334** [comment]
Last time somebody claimed this was an issue, I checked it statically and couldn't find a reason why it wouldn't work, also it worked for me on 16.6 last time I tried.

**Comment by savibb** [comment]
Maybe it’s the chip since you tried on 16.6 and it worked. 
I have a video sidebyside of a 14PM on 16.3.1 and a 12PM on 15.1. Using same Crane, sileo, dopamine, and trollstore version.
[video](https://file.io/q5d5FXIHfWLD)

Notice when I change the device identifier settings on the 14PM it reverts the Crane settings back to default. It doesn’t do that on the 12PM.

**Comment by savibb** [comment]
Would it help if I were to temporarily send you the 12 Pro Max running 16.1.2 to use to reproduce the issue. I have read at least two other reddit posts that mention this bug.

**Comment by opa334** [comment]
Fixed in 1.3.16-3.
