### ISSUE TITLE
[FEATURE] Backup and restore containers APIs

### ISSUE THREAD

**Issue by yur1xpp** [opa334/Crane-Resources#3]
Would love the APIs to backup and restore containers in addition to the current list of APIs. Thanks!

**Comment by opa334** [comment]
Not possible without essentially giving every process read/write access to the entire keychain, which would be a huge security issue.

**Comment by yur1xpp** [comment]
Fair point. The reason I request for such APIs is that backing up containers are repetitive and tedious if you have many containers for huge amount of apps, as the settings to do so is deep inside. Would it be possible to somehow add this feature to the Settings itself, for example buttons for:

- Backup All Containers
- Backup App with Containers (if it has container other than "Default")
- Backup Selected App Containers
- Restore All Containers 
- Restore App with Containers
- Restore Selected App Containers

If Crane itself have a CLI to achieve this is even better :)

*Such workflow will too ease the process of upgrading jailbreak, since backing up and restoring would be a single button job.

**Comment by opa334** [comment]
Again, a CLI would have the same security issue unfortunately. A future update will allow to backup multiple containers into one backup, I just have not yet gotten to it.

**Comment by yur1xpp** [comment]
That's fantastic news! :)
